export enum RmqPatterns {
    ORDER_REJECTED = 'ORDER_REJECTED',
    ORDER_APPROVED = 'ORDER_APPROVED',
    ORDER_CREATED = 'ORDER_CREATED',
    ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST',
    ORDER_PAYMENT_APPROVED = 'ORDER_PAYMENT_APPROVED',
    ORDER_PAYMENT_REJECTED = 'ORDER_PAYMENT_REJECTED',
    ORDER_COMPLETE_PAYMENT = 'ORDER_COMPLETE_PAYMENT',
    ORDER_PAYMENT_COMPLETED = 'ORDER_PAYMENT_COMPLETED',
    ORDER_ARCHIVED = 'ORDER_ARCHIVED',
}